# syntax=docker/dockerfile:1

FROM golang:1.24-alpine AS build
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/server ./{{if eq .Arch "simple"}}.{{else}}cmd/server{{end}}

FROM alpine:3.20
RUN adduser -D -u 10001 app
USER app
COPY --from=build /app/server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
